### PR TITLE
Changing plugin's prefix avoids old version conflicts

### PR DESCRIPTION
**Pull request by Adabaskar**
If plugin is invoced via the mvn goal "doxia:render-books" there is often a conflict with the older 1.2 Version plugin already being present and resolved via the prefix "doxia". Here it is proposed to change the plugin prefix to "doxia3" to avoid this conflict hence "mvn doxia3:render-books" should now be used.

### CODE REVIEW

**Comment by Adabaskar** [comment]
"would" rather than "should".
 Thx

**Comment by Adabaskar** [comment]
or maybe its more intuitive to change the artifactId ... ?

**Comment by hboutemy** [comment]
I suppose you're talking about doxia-book:render-books http://maven.apache.org/doxia/doxia-tools/doxia-book-maven-plugin/plugin-info.html

1.2 is the last release: 1.3 is still not released
I don't understand what you want to do

**Comment by Adabaskar** [comment]
@hboutemy Thanks for the polite comment in the face of my ignorance. I was (or still am) irritated by this: https://maven.apache.org/doxia/doxia-archives/doxia-1.2/doxia-maven-plugin/ therefore I was trying to invoke the plugin through doxia:render-books rather than doxia-book:render-books. I assumed that there were some resolution conflicts and therefore proposed to change the plugins prefix. This however is absolutely not necessary - excuse the nuisance. 

Anyway what is the difference between the doxia-maven-plugin and the doxia-book-maven-plugin, judging from the documentation I have found on the internet, both seem to be similar.

**Comment by hboutemy** [comment]
the plugin was extracted from Doxia core some time ago, before Doxia 1.3 was released: http://svn.apache.org/viewvc?view=revision&revision=1307847 and https://issues.apache.org/jira/browse/DOXIA-465
I should probably update old Doxia 1.2 documentation to explain this, since I completely understand how can have been confused.
And since there was no release since the extraction, I think the current Doxia 1.7 release train is the right moment to release doxia-book-maven-plugin 1.3

In general, one thing I have learned over years while maintaining Maven is that when someone has a surprising idea of code change, that's a sign that there is a surprising root cause: then asking for explanations is the good way to have a chance to find the root cause :)

**Pull request closed without merging**
